/**
 * Edge validation using the consensus tool adjacency matrix.
 *
 * Auto-generated by scripts/generateAdjacencyData.mjs — do not edit manually.
 *
 * Data sourced from:
 *   utils/consensus_connects/consensus_tool_adjacency_matrix.csv
 *   utils/{modality}_tests/connects/{modality}_tool_to_subsection_map.json
 *
 * VALID_EDGES: sparse map of source -> allowed targets (658 edges across 113 sources).
 * TOOL_META: tool -> [modality, subsection] for human-readable messages.
 */

const VALID_EDGES = {
    "3dANOVA": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dANOVA2": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dANOVA3": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dAutomask": ["3dANOVA", "3dANOVA2", "3dANOVA3", "3dDeconvolve", "3dLME", "3dLMEr", "3dMEMA", "3dMVM", "3dREMLfit", "3dttest++"],
    "3dBandpass": ["3dTshift"],
    "3dBlurToFWHM": ["3dAutomask"],
    "3dDeconvolve": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dDespike": ["3dTshift"],
    "3dLME": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dLMEr": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dMEMA": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dMVM": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dNetCorr": ["3dROIstats", "3dmaskave"],
    "3dNwarpApply": ["3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsJointLabelFusion.sh", "cluster", "whereami"],
    "3dNwarpCat": ["3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsJointLabelFusion.sh", "cluster", "whereami"],
    "3dREMLfit": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dRSFC": ["3dROIstats", "3dmaskave"],
    "3dSkullStrip": ["3dAllineate", "3dQwarp", "3dUnifize", "@auto_tlrc", "fast", "run_first_all"],
    "3dTcat": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp"],
    "3dTcorr1D": ["3dROIstats", "3dmaskave"],
    "3dTcorrMap": ["3dROIstats", "3dmaskave"],
    "3dTshift": ["align_epi_anat"],
    "3dTstat": ["3dNwarpApply", "3dNwarpCat", "3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsApplyTransforms", "antsJointLabelFusion.sh", "applywarp", "cluster", "convertwarp", "invwarp", "whereami"],
    "3dUndump": ["cluster"],
    "3dUnifize": ["3dAllineate", "3dQwarp", "@auto_tlrc"],
    "3dZeropad": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp"],
    "3dcalc": ["3dNwarpApply", "3dNwarpCat", "3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsApplyTransforms", "antsJointLabelFusion.sh", "applywarp", "cluster", "convertwarp", "invwarp", "whereami"],
    "3dcopy": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp"],
    "3dfractionize": ["cluster"],
    "3dinfo": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp"],
    "3dmerge": ["3dAutomask"],
    "3dresample": ["cluster"],
    "3dttest++": ["3dClustSim", "3dFWHMx", "3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap"],
    "3dvolreg": ["3dBlurToFWHM", "3dmerge"],
    "@SSwarper": ["3dAllineate", "3dQwarp", "3dUnifize", "@auto_tlrc", "fast", "run_first_all"],
    "Atropos": ["KellyKapowski", "antsCorticalThickness.sh"],
    "DenoiseImage": ["3dNwarpApply", "3dNwarpCat", "3dTcat", "3dTstat", "3dZeropad", "3dcalc", "3dcopy", "3dinfo", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslmerge", "fslreorient2std", "fslroi", "fslsplit", "fslstats", "invwarp", "mri_convert", "robustfov"],
    "ImageMath": ["3dNwarpApply", "3dNwarpCat", "3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsApplyTransforms", "antsJointLabelFusion.sh", "applywarp", "cluster", "convertwarp", "invwarp", "whereami"],
    "LabelGeometryMeasures": ["cluster"],
    "N4BiasFieldCorrection": ["3dNwarpApply", "3dNwarpCat", "3dTcat", "3dTstat", "3dZeropad", "3dcalc", "3dcopy", "3dinfo", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslmerge", "fslreorient2std", "fslroi", "fslsplit", "fslstats", "invwarp", "mri_convert", "robustfov"],
    "ThresholdImage": ["3dNwarpApply", "3dNwarpCat", "3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsApplyTransforms", "antsJointLabelFusion.sh", "applywarp", "cluster", "convertwarp", "invwarp", "whereami"],
    "align_epi_anat": ["3dvolreg"],
    "amico_noddi": ["amico_noddi"],
    "antsApplyTransforms": ["3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsJointLabelFusion.sh", "cluster", "whereami"],
    "antsAtroposN4.sh": ["KellyKapowski", "antsCorticalThickness.sh"],
    "antsBrainExtraction.sh": ["Atropos", "KellyKapowski", "antsAtroposN4.sh", "antsCorticalThickness.sh", "antsRegistration", "antsRegistrationSyN.sh", "antsRegistrationSyNQuick.sh", "fast", "run_first_all"],
    "antsIntermodalityIntrasubject.sh": ["antsIntermodalityIntrasubject.sh"],
    "antsJointLabelFusion.sh": ["cluster"],
    "antsMotionCorr": ["3dBandpass", "3dDespike", "dual_regression", "melodic"],
    "antsRegistration": ["KellyKapowski", "antsCorticalThickness.sh"],
    "antsRegistrationSyN.sh": ["KellyKapowski", "antsCorticalThickness.sh"],
    "antsRegistrationSyNQuick.sh": ["KellyKapowski", "antsCorticalThickness.sh"],
    "applytopup": ["mcflirt"],
    "applywarp": ["3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsJointLabelFusion.sh", "cluster", "whereami"],
    "asl_calib": ["asl_calib", "basil", "oxford_asl"],
    "basil": ["asl_calib", "basil", "oxford_asl"],
    "bbregister": ["wb_command_cifti_create_dense_timeseries", "wb_command_cifti_separate"],
    "bet": ["Atropos", "antsAtroposN4.sh", "fast", "flirt", "fnirt", "fsl_anat", "run_first_all", "siena", "sienax"],
    "convertwarp": ["3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsJointLabelFusion.sh", "cluster", "whereami"],
    "dtifit": ["tbss_1_preproc", "tbss_2_reg", "tbss_3_postreg", "tbss_4_prestats", "tbss_non_FA"],
    "dual_regression": ["susan"],
    "dwi2fod": ["tck2connectome", "tckgen", "tcksift"],
    "dwi2tensor": ["tck2connectome", "tckgen", "tcksift"],
    "dwidenoise": ["amico_noddi", "dtifit", "dwi2fod", "dwi2tensor", "tensor2metric"],
    "eddy": ["amico_noddi", "bedpostx", "dmri_postreg", "dtifit", "dwi2fod", "dwi2tensor", "probtrackx2", "tensor2metric"],
    "fast": ["bianca"],
    "flirt": ["antsRegistration", "antsRegistrationSyN.sh", "antsRegistrationSyNQuick.sh", "bianca"],
    "fmriprep": ["3dNetCorr", "3dRSFC", "3dTcorr1D", "3dTcorrMap", "bbregister", "film_gls", "flameo", "mri_glmfit", "mri_surf2vol", "mri_vol2surf", "mris_preproc", "randomise", "wb_command_cifti_create_dense_timeseries", "wb_command_cifti_separate"],
    "fnirt": ["antsRegistration", "antsRegistrationSyN.sh", "antsRegistrationSyNQuick.sh", "bianca"],
    "fsl_anat": ["bianca", "fast", "flirt", "fnirt", "run_first_all"],
    "fsl_prepare_fieldmap": ["mcflirt"],
    "fslmaths": ["3dNwarpApply", "3dNwarpCat", "3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsApplyTransforms", "antsJointLabelFusion.sh", "applywarp", "cluster", "convertwarp", "invwarp", "whereami"],
    "fslmeants": ["3dNwarpApply", "3dNwarpCat", "3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsApplyTransforms", "antsJointLabelFusion.sh", "applywarp", "cluster", "convertwarp", "invwarp", "whereami"],
    "fslmerge": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp"],
    "fslreorient2std": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp"],
    "fslroi": ["3dNwarpApply", "3dNwarpCat", "3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsApplyTransforms", "antsJointLabelFusion.sh", "applywarp", "cluster", "convertwarp", "invwarp", "whereami"],
    "fslsplit": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp"],
    "fslstats": ["3dNwarpApply", "3dNwarpCat", "3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsApplyTransforms", "antsJointLabelFusion.sh", "applywarp", "cluster", "convertwarp", "invwarp", "whereami"],
    "fugue": ["mcflirt"],
    "invwarp": ["3dUndump", "3dfractionize", "3dresample", "LabelGeometryMeasures", "antsJointLabelFusion.sh", "cluster", "whereami"],
    "mcflirt": ["slicetimer"],
    "melodic": ["susan"],
    "mrdegibbs": ["amico_noddi", "dtifit", "dwi2fod", "dwi2tensor", "tensor2metric"],
    "mri_annotation2label": ["aparcstats2table", "asegstats2table", "mri_segstats", "mris_anatomical_stats"],
    "mri_aparc2aseg": ["aparcstats2table", "asegstats2table", "mri_segstats", "mris_anatomical_stats"],
    "mri_convert": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "aparcstats2table", "applywarp", "asegstats2table", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp", "mri_annotation2label", "mri_aparc2aseg", "mri_label2vol", "mri_segstats", "mris_anatomical_stats", "mris_ca_label", "wb_command_surface_sphere_project_unproject"],
    "mri_glmfit": ["wb_command_cifti_create_dense_timeseries", "wb_command_cifti_separate"],
    "mri_gtmpvc": ["mri_gtmpvc"],
    "mri_label2vol": ["aparcstats2table", "asegstats2table", "mri_segstats", "mris_anatomical_stats"],
    "mri_normalize": ["aparcstats2table", "asegstats2table", "mri_annotation2label", "mri_aparc2aseg", "mri_label2vol", "mri_segstats", "mris_anatomical_stats", "mris_ca_label", "wb_command_surface_sphere_project_unproject"],
    "mri_segment": ["aparcstats2table", "asegstats2table", "mri_annotation2label", "mri_aparc2aseg", "mri_label2vol", "mri_segstats", "mris_anatomical_stats", "mris_ca_label", "wb_command_surface_sphere_project_unproject"],
    "mri_surf2vol": ["wb_command_cifti_create_dense_timeseries", "wb_command_cifti_separate"],
    "mri_vol2surf": ["wb_command_cifti_create_dense_timeseries", "wb_command_cifti_separate"],
    "mri_watershed": ["aparcstats2table", "asegstats2table", "mri_annotation2label", "mri_aparc2aseg", "mri_label2vol", "mri_segstats", "mris_anatomical_stats", "mris_ca_label", "wb_command_surface_sphere_project_unproject"],
    "mriqc": ["3dvolreg", "antsMotionCorr", "fmriprep", "mcflirt"],
    "mris_ca_label": ["aparcstats2table", "asegstats2table", "mri_segstats", "mris_anatomical_stats"],
    "mris_inflate": ["aparcstats2table", "asegstats2table", "mri_annotation2label", "mri_aparc2aseg", "mri_label2vol", "mri_segstats", "mris_anatomical_stats", "mris_ca_label", "wb_command_surface_sphere_project_unproject"],
    "mris_preproc": ["wb_command_cifti_create_dense_timeseries", "wb_command_cifti_separate"],
    "mris_sphere": ["aparcstats2table", "asegstats2table", "mri_annotation2label", "mri_aparc2aseg", "mri_label2vol", "mri_segstats", "mris_anatomical_stats", "mris_ca_label", "wb_command_surface_sphere_project_unproject"],
    "oxford_asl": ["asl_calib", "basil", "oxford_asl"],
    "prelude": ["mcflirt"],
    "recon-all": ["aparcstats2table", "asegstats2table", "mri_annotation2label", "mri_aparc2aseg", "mri_label2vol", "mri_segstats", "mris_anatomical_stats", "mris_ca_label", "wb_command_surface_sphere_project_unproject"],
    "robustfov": ["3dNwarpApply", "3dNwarpCat", "3dTstat", "3dcalc", "ImageMath", "ThresholdImage", "antsApplyTransforms", "applywarp", "convertwarp", "fslmaths", "fslmeants", "fslroi", "fslstats", "invwarp"],
    "run_first_all": ["bianca"],
    "siena": ["bianca", "fast", "flirt", "fnirt", "run_first_all"],
    "sienax": ["bianca", "fast", "flirt", "fnirt", "run_first_all"],
    "slicetimer": ["dual_regression", "melodic"],
    "susan": ["film_gls", "flameo", "randomise"],
    "tensor2metric": ["tck2connectome", "tckgen", "tcksift"],
    "topup": ["amico_noddi", "bedpostx", "dmri_postreg", "dtifit", "dwi2fod", "dwi2tensor", "mcflirt", "probtrackx2", "tensor2metric"],
    "wb_command_cifti_create_dense_timeseries": ["wb_command_cifti_smoothing", "wb_command_metric_smoothing"],
    "wb_command_cifti_separate": ["wb_command_cifti_smoothing", "wb_command_metric_smoothing"],
    "whereami": ["cluster"]
};

const TOOL_META = {
    "3dANOVA": ["Functional MRI", "Statistical Analysis"],
    "3dANOVA2": ["Functional MRI", "Statistical Analysis"],
    "3dANOVA3": ["Functional MRI", "Statistical Analysis"],
    "3dAllineate": ["Structural MRI", "Registration"],
    "3dAutomask": ["Functional MRI", "Masking"],
    "3dBandpass": ["Functional MRI", "Denoising"],
    "3dBlurToFWHM": ["Functional MRI", "Smoothing"],
    "3dClustSim": ["Functional MRI", "Multiple Comparisons"],
    "3dDeconvolve": ["Functional MRI", "Statistical Analysis"],
    "3dDespike": ["Functional MRI", "Denoising"],
    "3dFWHMx": ["Functional MRI", "Multiple Comparisons"],
    "3dLME": ["Functional MRI", "Statistical Analysis"],
    "3dLMEr": ["Functional MRI", "Statistical Analysis"],
    "3dMEMA": ["Functional MRI", "Statistical Analysis"],
    "3dMVM": ["Functional MRI", "Statistical Analysis"],
    "3dNetCorr": ["Functional MRI", "Connectivity"],
    "3dNwarpApply": ["Utilities", "Warp Utilities"],
    "3dNwarpCat": ["Utilities", "Warp Utilities"],
    "3dQwarp": ["Structural MRI", "Registration"],
    "3dREMLfit": ["Functional MRI", "Statistical Analysis"],
    "3dROIstats": ["Functional MRI", "ROI Analysis"],
    "3dRSFC": ["Functional MRI", "Connectivity"],
    "3dSkullStrip": ["Structural MRI", "Brain Extraction"],
    "3dTcat": ["Utilities", "Dataset Operations"],
    "3dTcorr1D": ["Functional MRI", "Connectivity"],
    "3dTcorrMap": ["Functional MRI", "Connectivity"],
    "3dTshift": ["Functional MRI", "Slice Timing"],
    "3dTstat": ["Utilities", "Image Math"],
    "3dUndump": ["Utilities", "ROI Utilities"],
    "3dUnifize": ["Structural MRI", "Bias Correction"],
    "3dZeropad": ["Utilities", "Dataset Operations"],
    "3dcalc": ["Utilities", "Image Math"],
    "3dcopy": ["Utilities", "Dataset Operations"],
    "3dfractionize": ["Utilities", "ROI Utilities"],
    "3dinfo": ["Utilities", "Dataset Operations"],
    "3dmaskave": ["Functional MRI", "ROI Analysis"],
    "3dmerge": ["Functional MRI", "Smoothing"],
    "3dresample": ["Utilities", "ROI Utilities"],
    "3dttest++": ["Functional MRI", "Statistical Analysis"],
    "3dvolreg": ["Functional MRI", "Motion Correction"],
    "@SSwarper": ["Structural MRI", "Brain Extraction"],
    "@auto_tlrc": ["Structural MRI", "Registration"],
    "Atropos": ["Structural MRI", "Segmentation"],
    "DenoiseImage": ["Utilities", "Preprocessing Utilities"],
    "ImageMath": ["Utilities", "Image Operations"],
    "KellyKapowski": ["Structural MRI", "Cortical Thickness"],
    "LabelGeometryMeasures": ["Utilities", "Label Analysis"],
    "N4BiasFieldCorrection": ["Utilities", "Preprocessing Utilities"],
    "ThresholdImage": ["Utilities", "Image Operations"],
    "align_epi_anat": ["Functional MRI", "Registration"],
    "amico_noddi": ["Accelerated Microstructure Imaging via Convex Optimization/Diffusion Magnetic Resonance Imaging", "Microstructure Modeling"],
    "antsApplyTransforms": ["Utilities", "Transform Utilities"],
    "antsAtroposN4.sh": ["Structural MRI", "Segmentation"],
    "antsBrainExtraction.sh": ["Structural MRI", "Brain Extraction"],
    "antsCorticalThickness.sh": ["Structural MRI", "Cortical Thickness"],
    "antsIntermodalityIntrasubject.sh": ["Multimodal", "Intermodal Registration"],
    "antsJointLabelFusion.sh": ["Utilities", "Label Analysis"],
    "antsMotionCorr": ["Functional MRI", "Motion Correction"],
    "antsRegistration": ["Structural MRI", "Registration"],
    "antsRegistrationSyN.sh": ["Structural MRI", "Registration"],
    "antsRegistrationSyNQuick.sh": ["Structural MRI", "Registration"],
    "aparcstats2table": ["Structural MRI", "Morphometry"],
    "applytopup": ["Functional MRI", "Distortion Correction"],
    "applywarp": ["Utilities", "Warp Utilities"],
    "asegstats2table": ["Structural MRI", "Morphometry"],
    "asl_calib": ["Arterial Spin Labeling", "ASL Processing"],
    "basil": ["Arterial Spin Labeling", "ASL Processing"],
    "bbregister": ["Functional MRI", "Functional Analysis"],
    "bedpostx": ["Diffusion Magnetic Resonance Imaging", "Tractography"],
    "bet": ["Structural MRI", "Brain Extraction"],
    "bianca": ["Structural MRI", "Lesion Segmentation"],
    "cluster": ["Utilities", "Clustering"],
    "convertwarp": ["Utilities", "Warp Utilities"],
    "dmri_postreg": ["Diffusion Magnetic Resonance Imaging", "Diffusion"],
    "dtifit": ["Diffusion Magnetic Resonance Imaging", "Tensor Fitting"],
    "dual_regression": ["Functional MRI", "ICA/Denoising"],
    "dwi2fod": ["Diffusion Magnetic Resonance Imaging", "Tensor/FOD"],
    "dwi2tensor": ["Diffusion Magnetic Resonance Imaging", "Tensor/FOD"],
    "dwidenoise": ["Diffusion Magnetic Resonance Imaging", "Preprocessing"],
    "eddy": ["Diffusion Magnetic Resonance Imaging", "Preprocessing"],
    "fast": ["Structural MRI", "Tissue Segmentation"],
    "film_gls": ["Functional MRI", "Statistical Analysis"],
    "flameo": ["Functional MRI", "Statistical Analysis"],
    "flirt": ["Structural MRI", "Registration"],
    "fmriprep": ["Functional MRI", "Pipeline"],
    "fnirt": ["Structural MRI", "Registration"],
    "fsl_anat": ["Structural MRI", "Pipelines"],
    "fsl_prepare_fieldmap": ["Functional MRI", "Distortion Correction"],
    "fslmaths": ["Utilities", "Image Math"],
    "fslmeants": ["Utilities", "Image Math"],
    "fslmerge": ["Utilities", "Volume Operations"],
    "fslreorient2std": ["Utilities", "Volume Operations"],
    "fslroi": ["Utilities", "Image Math"],
    "fslsplit": ["Utilities", "Volume Operations"],
    "fslstats": ["Utilities", "Image Math"],
    "fugue": ["Functional MRI", "Distortion Correction"],
    "invwarp": ["Utilities", "Warp Utilities"],
    "mcflirt": ["Functional MRI", "Motion Correction"],
    "melodic": ["Functional MRI", "ICA/Denoising"],
    "mrdegibbs": ["Diffusion Magnetic Resonance Imaging", "Preprocessing"],
    "mri_annotation2label": ["Structural MRI", "Parcellation"],
    "mri_aparc2aseg": ["Structural MRI", "Parcellation"],
    "mri_convert": ["Structural MRI/Utilities", "Surface Reconstruction"],
    "mri_glmfit": ["Functional MRI", "Functional Analysis"],
    "mri_gtmpvc": ["Positron Emission Tomography", "PET Processing"],
    "mri_label2vol": ["Structural MRI", "Parcellation"],
    "mri_normalize": ["Structural MRI", "Surface Reconstruction"],
    "mri_segment": ["Structural MRI", "Surface Reconstruction"],
    "mri_segstats": ["Structural MRI", "Morphometry"],
    "mri_surf2vol": ["Functional MRI", "Functional Analysis"],
    "mri_vol2surf": ["Functional MRI", "Functional Analysis"],
    "mri_watershed": ["Structural MRI", "Surface Reconstruction"],
    "mriqc": ["Functional MRI", "Pipeline"],
    "mris_anatomical_stats": ["Structural MRI", "Morphometry"],
    "mris_ca_label": ["Structural MRI", "Parcellation"],
    "mris_inflate": ["Structural MRI", "Surface Reconstruction"],
    "mris_preproc": ["Functional MRI", "Functional Analysis"],
    "mris_sphere": ["Structural MRI", "Surface Reconstruction"],
    "oxford_asl": ["Arterial Spin Labeling", "ASL Processing"],
    "prelude": ["Functional MRI", "Distortion Correction"],
    "probtrackx2": ["Diffusion Magnetic Resonance Imaging", "Tractography"],
    "randomise": ["Functional MRI", "Statistical Analysis"],
    "recon-all": ["Structural MRI", "Surface Reconstruction"],
    "robustfov": ["Utilities", "Volume Operations"],
    "run_first_all": ["Structural MRI", "Tissue Segmentation"],
    "siena": ["Structural MRI", "Pipelines"],
    "sienax": ["Structural MRI", "Pipelines"],
    "slicetimer": ["Functional MRI", "Slice Timing"],
    "susan": ["Functional MRI", "Smoothing"],
    "tbss_1_preproc": ["Diffusion Magnetic Resonance Imaging", "TBSS"],
    "tbss_2_reg": ["Diffusion Magnetic Resonance Imaging", "TBSS"],
    "tbss_3_postreg": ["Diffusion Magnetic Resonance Imaging", "TBSS"],
    "tbss_4_prestats": ["Diffusion Magnetic Resonance Imaging", "TBSS"],
    "tbss_non_FA": ["Diffusion Magnetic Resonance Imaging", "TBSS"],
    "tck2connectome": ["Diffusion Magnetic Resonance Imaging", "Tractography"],
    "tckgen": ["Diffusion Magnetic Resonance Imaging", "Tractography"],
    "tcksift": ["Diffusion Magnetic Resonance Imaging", "Tractography"],
    "tensor2metric": ["Diffusion Magnetic Resonance Imaging", "Tensor/FOD"],
    "topup": ["Diffusion Magnetic Resonance Imaging/Functional MRI", "Preprocessing"],
    "wb_command_cifti_create_dense_timeseries": ["Functional MRI", "CIFTI Operations"],
    "wb_command_cifti_separate": ["Functional MRI", "CIFTI Operations"],
    "wb_command_cifti_smoothing": ["Functional MRI", "Surface Smoothing"],
    "wb_command_metric_smoothing": ["Functional MRI", "Surface Smoothing"],
    "wb_command_surface_sphere_project_unproject": ["Structural MRI", "Surface Registration"],
    "whereami": ["Utilities", "ROI Utilities"]
};

// Precompute Set-based lookup for O(1) edge checks
const _edgeSets = new Map();
for (const [src, targets] of Object.entries(VALID_EDGES)) {
    _edgeSets.set(src, new Set(targets));
}

/**
 * Check whether a directed tool connection is valid per the consensus matrix.
 * Returns true for any connection involving unknown tools (not in the matrix).
 */
export function isValidToolConnection(sourceLabel, targetLabel) {
    if (!sourceLabel || !targetLabel) return true;
    if (!TOOL_META[sourceLabel] || !TOOL_META[targetLabel]) return true;
    const allowed = _edgeSets.get(sourceLabel);
    return allowed ? allowed.has(targetLabel) : false;
}

/**
 * Return a human-readable reason why a connection is invalid.
 * Returns null if the connection is valid or involves unknown tools.
 */
export function getInvalidConnectionReason(sourceLabel, targetLabel) {
    if (isValidToolConnection(sourceLabel, targetLabel)) return null;

    const srcMeta = TOOL_META[sourceLabel];
    const dstMeta = TOOL_META[targetLabel];
    if (!srcMeta || !dstMeta) return null;

    const [srcMod, srcSub] = srcMeta;
    const [dstMod, dstSub] = dstMeta;

    // Check cross-modality (account for multi-modality tools like topup)
    const srcMods = srcMod.split('/');
    const dstMods = dstMod.split('/');
    const shareModality = srcMods.some(m => dstMods.includes(m));

    if (!shareModality) {
        return `Cross-modality: ${srcMods[0]} \u2192 ${dstMods[0]} is not a standard connection.`;
    }

    // Same modality but invalid pipeline connection
    if (!_edgeSets.has(sourceLabel)) {
        return `${sourceLabel} (${srcSub}) is a terminal tool with no standard downstream connections.`;
    }

    return `No standard pipeline connection from ${srcSub} \u2192 ${dstSub}.`;
}
