/**
 * Build ro-crate-metadata.json content conforming to the
 * Workflow RO-Crate 1.0 profile (https://w3id.org/workflowhub/workflow-ro-crate/1.0).
 *
 * Returns a JSON string — no external dependencies needed.
 */

/**
 * @param {Object} params
 * @param {string} params.workflowName      - Sanitized workflow name
 * @param {string} params.mainWorkflowPath  - e.g. "workflows/my_pipeline.cwl"
 * @param {string} params.jobTemplatePath   - e.g. "workflows/my_pipeline_job.yml"
 * @param {string[]} params.toolCWLPaths    - e.g. ["cwl/fsl/bet.cwl", ...]
 * @param {Object}  params.toolMetadata     - { [cwlPath]: { fullName, docUrl } }
 * @param {string[]} params.dockerImages    - e.g. ["brainlife/fsl:6.0.5", ...]
 * @returns {string} JSON string for ro-crate-metadata.json
 */
export function buildROCrateMetadata({
    workflowName,
    mainWorkflowPath,
    jobTemplatePath,
    toolCWLPaths,
    toolMetadata,
    dockerImages,
}) {
    const graph = [];

    /* ---- Metadata File Descriptor ---- */
    graph.push({
        '@id': 'ro-crate-metadata.json',
        '@type': 'CreativeWork',
        about: { '@id': './' },
        conformsTo: [
            { '@id': 'https://w3id.org/ro/crate/1.1' },
            { '@id': 'https://w3id.org/workflowhub/workflow-ro-crate/1.0' },
        ],
    });

    /* ---- hasPart list (all data entities) ---- */
    const hasPart = [
        { '@id': mainWorkflowPath },
        { '@id': jobTemplatePath },
        { '@id': 'README.md' },
        { '@id': 'Dockerfile' },
        { '@id': 'run.sh' },
        { '@id': 'prefetch_images.sh' },
        ...toolCWLPaths.map(p => ({ '@id': p })),
    ];

    /* ---- Root Data Entity ---- */
    graph.push({
        '@id': './',
        '@type': 'Dataset',
        name: workflowName,
        description: `Neuroimaging CWL workflow generated by niBuild containing ${toolCWLPaths.length} processing step(s).`,
        datePublished: new Date().toISOString().slice(0, 10),
        license: { '@id': 'https://spdx.org/licenses/MIT' },
        mainEntity: { '@id': mainWorkflowPath },
        hasPart,
    });

    /* ---- Main Workflow ---- */
    graph.push({
        '@id': mainWorkflowPath,
        '@type': ['File', 'SoftwareSourceCode', 'ComputationalWorkflow'],
        name: workflowName,
        programmingLanguage: { '@id': '#cwl' },
    });

    /* ---- CWL Language (contextual entity) ---- */
    graph.push({
        '@id': '#cwl',
        '@type': 'ComputerLanguage',
        name: 'Common Workflow Language',
        alternateName: 'CWL',
        identifier: { '@id': 'https://w3id.org/cwl/v1.2/' },
        url: { '@id': 'https://www.commonwl.org/' },
    });

    /* ---- Job Template ---- */
    graph.push({
        '@id': jobTemplatePath,
        '@type': 'File',
        name: 'Job input template',
        description: 'Pre-configured parameter values for running the workflow',
    });

    /* ---- Tool CWL files ---- */
    for (const p of toolCWLPaths) {
        const meta = toolMetadata[p];
        const entity = {
            '@id': p,
            '@type': ['File', 'SoftwareSourceCode'],
            name: meta?.fullName || p,
            programmingLanguage: { '@id': '#cwl' },
        };
        if (meta?.docUrl) {
            entity.url = { '@id': meta.docUrl };
        }
        graph.push(entity);
    }

    /* ---- Docker images ---- */
    for (const img of dockerImages) {
        const [repo] = img.split(':');
        graph.push({
            '@id': `https://hub.docker.com/r/${repo}`,
            '@type': 'SoftwareApplication',
            name: img,
            url: `https://hub.docker.com/r/${repo}`,
        });
    }

    /* ---- README ---- */
    graph.push({
        '@id': 'README.md',
        '@type': 'File',
        name: 'README',
        encodingFormat: 'text/markdown',
    });

    /* ---- Dockerfile ---- */
    graph.push({
        '@id': 'Dockerfile',
        '@type': 'File',
        name: 'Dockerfile',
        description: 'Orchestration container for Docker-based workflow execution',
    });

    /* ---- Support scripts ---- */
    graph.push({
        '@id': 'run.sh',
        '@type': 'File',
        name: 'Run script',
        description: 'Entrypoint script with usage help',
    });

    graph.push({
        '@id': 'prefetch_images.sh',
        '@type': 'File',
        name: 'Image prefetch script',
        description: 'Pre-pull tool Docker images',
    });

    return JSON.stringify(
        {
            '@context': 'https://w3id.org/ro/crate/1.1/context',
            '@graph': graph,
        },
        null,
        2
    );
}
